/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class JsExecutor {
  static fromConfig(configJson: string): JsExecutor
  spawn(cwd: string, prompt: string, env?: Record<string, string> | undefined | null): Promise<JsChild>
}
export declare class JsChild {
  streamOutput(callback: (arg: string) => any): void
  wait(): Promise<number>
  kill(): Promise<void>
}
